platform:ios, '8.0'
target 'DeeDao' do
pod 'PGDatePicker'
pod 'BGNetwork'
pod 'YYText', '~> 1.0.7'
pod 'IQKeyboardManager', '~> 5.0.8'
pod 'Masonry', '~> 1.1.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'MJExtension', '~> 3.0.13'
pod 'Qiniu', '~> 7.1'
pod 'TZImagePickerController', '~> 3.0.7'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'BaiduMapKit', '~> 4.1.1'
pod 'WechatOpenSDK'
pod 'PPGetAddressBook', '~> 0.2.8'
pod 'LGSideMenuController', '~> 2.1.1'
end
